wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.2
    framework: lightgbm
    huggingface_version: 4.28.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683314704.986297
    t:
      1:
      - 1
      - 5
      - 6
      - 7
      - 8
      - 9
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 7
      - 8
      - 9
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.13
      5: 0.14.2
      6: 4.28.1
      8:
      - 1
      - 4
      - 5
